/**
 * Weekly data-refresh orchestrator.
 *
 * For each wired category: fetch the newest source file from SharePoint, then
 * run that category's extractor against the downloaded file. The extractors
 * write the dashboard JSON in public/data/, which the workflow commits.
 *
 * Behavior designed for hands-off operation:
 *  - Each category is isolated; one bad file never blocks the others.
 *  - A category whose folder has files but none matching the naming convention
 *    is treated as a FAILURE (so a typo'd upload doesn't silently skip).
 *  - An empty folder (no file yet) is a normal skip, not a failure.
 *  - A category with a `published` provenance getter is skipped when
 *    SharePoint's newest file is the one already published (see below).
 *  - A per-run summary is written to refresh-summary.txt (used by the email).
 *  - Exit non-zero if any category failed, so the workflow marks the run failed
 *    and sends the alert email.
 *
 * Usage:
 *   node scripts/refresh-data.mjs            # all wired categories
 *   node scripts/refresh-data.mjs idiq       # only the named categories
 *   node scripts/refresh-data.mjs --force    # re-run even if already published
 */
import { execFileSync } from "node:child_process";
import { writeFileSync, readFileSync } from "node:fs";
import { inspectCategory, fetchCategory } from "./sharepoint/fetch.mjs";
import { loadLocalEnv } from "./sharepoint/graph.mjs";

// Category key (must match fetch.mjs CATEGORIES) -> Python extractor.
// The downloaded file path is passed as argv[1] to each extractor.
//
// `published` (optional) returns the provenance the category recorded in its
// last published output: { source, sourceModified }. When it matches the newest
// file in SharePoint, the category is skipped without downloading or
// re-extracting. Only SITREP uses it: its extractor is the one that costs money
// (a Claude API call per run) and it re-parses from scratch every time, so
// re-running it on a file we already published is pure waste. It is also not
// idempotent: because the digest is regenerated by the model, an identical
// input can still yield slightly different JSON and a spurious commit.
const WIRED = {
  finance: { script: "scripts/extractActualsData.py" },
  idiq: { script: "scripts/extractIdiqData.py" },
  safety: { script: "scripts/extractSafetyData.py" },
  sitrep: {
    runner: "node",
    script: "scripts/extractSitrep.mjs",
    published: () => readJson("public/data/sitrep.json"),
  },
  staffing: { script: "scripts/extractStaffingData.py" },
  turf: { script: "scripts/extractTurfData.py" },
};

/** Parse a JSON file; null if missing or unparseable. */
function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null; // no output published yet, or unparseable -> run the extractor
  }
}

/**
 * Has this exact file already been published? Matches on filename AND the
 * SharePoint upload timestamp, so a corrected re-upload of the same month is
 * treated as new work rather than skipped.
 *
 * Compare against the CANONICALIZED name, not newest.name: SITREPs arrive under
 * human-readable names ("2026.08_Regional Director's SITREP_August 2026.pdf")
 * and the fetch saves them as sitrep_YYYY-MM.<ext>, which is what the published
 * digest records. Comparing raw names would never match and this would silently
 * never fire.
 *
 * Outputs published before `sourceModified` existed fall back to a name-only
 * match, so an old output degrades to the previous behavior instead of forcing
 * one throwaway re-parse.
 */
function alreadyPublished(published, newest) {
  if (!published || published.source !== newest.normalizedName) return false;
  if (!published.sourceModified) return true; // pre-timestamp output
  return published.sourceModified === newest.lastModified;
}

loadLocalEnv(); // no-op in CI where SHAREPOINT_* come from secrets

const argv = process.argv.slice(2);
const force = argv.includes("--force");
const requested = argv.filter((a) => !a.startsWith("-"));
const keys = requested.length ? requested : Object.keys(WIRED);

const results = [];
for (const key of keys) {
  if (!WIRED[key]) {
    console.error(`! ${key}: not a wired category, skipping`);
    continue;
  }
  console.log(`\n=== ${key} ===`);
  try {
    const { newest, skipped } = await inspectCategory(key);
    if (!newest) {
      if (skipped.length) {
        throw new Error(`files present but none match the naming convention: ${skipped.join(", ")}`);
      }
      console.log("  no file in SharePoint yet — skipping");
      results.push({ key, status: "skipped", detail: "no file uploaded yet" });
      continue;
    }
    if (alreadyPublished(WIRED[key].published?.(), newest)) {
      const label = `${newest.normalizedName} (uploaded ${newest.lastModified})`;
      if (force) {
        console.log(`  ${label} already published, re-running anyway (--force)`);
      } else {
        console.log(`  ${label} already published, skipping (--force to re-run)`);
        results.push({ key, status: "skipped", detail: `${newest.normalizedName} already parsed` });
        continue;
      }
    }
    const fetched = await fetchCategory(key);
    console.log(`  fetched ${fetched.name}`);
    const runner = WIRED[key].runner || "python3";
    // Hand the extractor the upload timestamp so it can record which exact
    // revision of the file this output came from.
    execFileSync(runner, [WIRED[key].script, fetched.dest], {
      stdio: "inherit",
      env: { ...process.env, REFRESH_SOURCE_MODIFIED: newest.lastModified || "" },
    });
    results.push({ key, status: "refreshed", detail: fetched.name });
  } catch (e) {
    console.error(`  FAILED: ${e.message}`);
    results.push({ key, status: "failed", detail: e.message });
  }
}

const summary = results
  .map((r) => `${r.status.toUpperCase().padEnd(9)} ${r.key}: ${r.detail}`)
  .join("\n");
writeFileSync("refresh-summary.txt", summary + "\n");

const counts = {
  refreshed: results.filter((r) => r.status === "refreshed").length,
  skipped: results.filter((r) => r.status === "skipped").length,
  failed: results.filter((r) => r.status === "failed").length,
};
console.log(`\n${summary}`);
console.log(`\n${counts.refreshed} refreshed, ${counts.skipped} skipped, ${counts.failed} failed.`);

if (counts.failed) process.exit(1);
